/**
 * CapCut draft format constants.
 *
 * Verified against a real CapCut 8.7.0 draft on macOS and real Windows-authored
 * drafts (CapCut 3.9 / 8.5). See README "How it works" for the format notes.
 */

/**
 * CapCut's draft-relative path placeholder. The UUID is a fixed constant baked
 * into CapCut itself — identical on macOS and Windows across all observed
 * versions (2.8 → 8.7). CapCut substitutes the draft folder path at load time.
 */
export const DRAFT_PATH_PLACEHOLDER =
  '##_draftpath_placeholder_0E685133-18CE-45ED-8CB8-2904A212EC80_##'

/**
 * Timeline filenames by app generation: current macOS writes draft_info.json,
 * Windows (and older macOS) writes draft_content.json. Probe in this order.
 */
export const TIMELINE_FILENAMES = ['draft_info.json', 'draft_content.json'] as const
export type TimelineFilename = (typeof TIMELINE_FILENAMES)[number]

export const TIMELINE_FILENAME_FOR_OS: Record<'mac' | 'windows', TimelineFilename> = {
  mac: 'draft_info.json',
  windows: 'draft_content.json'
}

/** Per-draft metadata file (same name on both OSes). */
export const DRAFT_META_FILENAME = 'draft_meta_info.json'

/** Root-level registry CapCut maintains one level above the draft folders. */
export const ROOT_META_FILENAME = 'root_meta_info.json'

export const DRAFT_COVER_FILENAME = 'draft_cover.jpg'

/** The shared draft directory name under <User Data>/Projects/ on both OSes. */
export const DRAFT_DIR_NAME = 'com.lveditor.draft'

/**
 * Marker that identifies CapCut effect/asset cache paths inside draft JSON
 * (always written with forward slashes, on both OSes).
 */
export const CACHE_PATH_MARKER = '/CapCut/User Data/Cache/'

/**
 * Directories regenerated by CapCut on demand — excluded from lean exports.
 * All are AI/analysis caches; the sample project carried 65 MB of 99 MB here.
 */
export const REGENERABLE_DIRS = [
  'matting',
  'smart_crop',
  'adjust_mask',
  'qr_upload',
  'Resources/audioAlg',
  'Resources/videoAlg',
  'materials/videoTracking'
] as const

/**
 * Files never packed into a .capshare and dropped on import: CapCut backups /
 * template clones that duplicate the timeline (and its machine-specific paths).
 */
export const VOLATILE_FILE_PATTERNS = [/\.bak$/i, /\.backup$/i, /^template(-\d+)?\.tmp$/i] as const

/** OS junk never packed. */
export const JUNK_FILE_NAMES = new Set(['.DS_Store', 'Thumbs.db', 'desktop.ini'])

/** Hidden root-level dirs that are not drafts. */
export const NON_DRAFT_DIR_PATTERN = /^\./

/** The schema constant CapCut has used for `version` since at least 2.8. */
export const DRAFT_SCHEMA_VERSION = 360000
